### ISSUE TITLE
why I can not found the file naming segementation  in my datasets directory?

### ISSUE THREAD

**Issue by xxxolllllllll** [EricYu97/UAD-RS#3]

**Comment by xxxolllllllll** [comment]
My teacher asked me to run the some code like this,but I encountered the problem.

**Comment by EricYu97** [comment]
Hi,

Thank you for your interest in our research! The segmentation folder is contained in the UAE-RS directory, for which we use to craft adversarial examples. Before running the experiments for adversarial purification, you will need to generate adversarial examples first, as introduced in the instructions. 

More information for UAE-RS can be found here: https://github.com/YonghaoXu/UAE-RS

Good luck!
